export const NAV_LINKS = [
  { href: "/", label: "Command Deck" },
  { href: "/transactions", label: "Transactions" },
  { href: "/income", label: "Income" },
  { href: "/transfers", label: "Transfers" },
  { href: "/weekly-rollup", label: "Weekly Rollup" },
  { href: "/monthly-rollup", label: "Monthly Rollup" },
  { href: "/recurring-bills", label: "Recurring" },
  { href: "/savings-goals", label: "Savings Goals" },
  { href: "/net-worth", label: "Net Worth" },
  { href: "/semester-planner", label: "Budget Periods" },
  { href: "/insights", label: "Insights" },
  { href: "/key-dates", label: "Key Dates" },
  { href: "/import", label: "Import" },
  { href: "/audit-log", label: "Audit Log" },
  { href: "/settings", label: "Settings" },
] as const;
